"""
Alert model - notifications requiring attention
"""

from sqlalchemy import String, Text, Boolean, ForeignKey, DateTime, JSON, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from datetime import datetime
from typing import Optional

from .base import Base, generate_uuid


class Alert(Base):
    """
    Alert requiring user attention.
    Generated by monitoring agents.
    """

    __tablename__ = "alerts"

    # Primary key
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)

    # Foreign key to fund
    fund_id: Mapped[str] = mapped_column(String(36), ForeignKey("funds.id", ondelete="CASCADE"))

    # Alert details
    type: Mapped[str] = mapped_column(String(50), nullable=False)  # news, drift, risk, opportunity, earnings
    ticker: Mapped[Optional[str]] = mapped_column(String(20))
    title: Mapped[Optional[str]] = mapped_column(String(255))
    message: Mapped[Optional[str]] = mapped_column(Text)

    # Severity
    severity: Mapped[Optional[str]] = mapped_column(String(20))  # info, warning, critical

    # Action
    action_required: Mapped[bool] = mapped_column(Boolean, default=False)
    action_options: Mapped[Optional[dict]] = mapped_column(JSON)  # ["hold", "trim", "sell"]

    # Status
    status: Mapped[str] = mapped_column(String(20), default="pending")  # pending, resolved, dismissed

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime)

    # Relationships
    fund: Mapped["Fund"] = relationship("Fund", back_populates="alerts")

    def __repr__(self) -> str:
        return f"<Alert(type='{self.type}', severity='{self.severity}')>"

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "fund_id": self.fund_id,
            "type": self.type,
            "ticker": self.ticker,
            "title": self.title,
            "message": self.message,
            "severity": self.severity,
            "action_required": self.action_required,
            "action_options": self.action_options,
            "status": self.status,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
        }
